### ISSUE TITLE
Typ für angehängte Dokumente einführen

### ISSUE THREAD

**Issue by saerdnaer** [codeformunich/muenchen-transparent#104]
Können wir für zukünftige Features einen Typ für die einzelnen Dokumente einführen. Ich denke da an sowas wie "Text", "Karte", "Foto/Bild" vgl. https://www.muenchen-transparent.de/antraege/3630814

**Comment by konstin** [comment]
Leider steht der Typ des Dokuments nicht im RIS, weshalb wir ihn auch nicht automatisiert erfassen können. Die Alternative wäre, das bei jedem Dokument per Hand einzutragen, was aber zu einem unrealitischen Aufwand führen würde. Außerdem sollte man eigentlich schon am Titel eines Dokuments ablesen können, was sich darin befindet.

**Comment by saerdnaer** [comment]
Ja, ist klar das müsste man manuell erfassen bzw. ggf. auch automatisch aus dem Text ableiten. Mir geht es halt darum dann z.B. bei Fotos nachträglich auch eine Koordinaten anhängen zu können, oder bei Plänen eine Bounding Box. 
Klar das wird man nicht für alle Anträge automatisieren können, aber ich wenn einzelne Leute Lust haben so Zeug aufzubereiten würde ich die Möglichkeit anbieten

**Comment by konstin** [comment]
Vielleicht wäre es dafür sinnvoller, einfach nur für jedes Dokument die Möglichkeit einzuführen, bestimmte Informationen, wie z.B. Koordinaten, damit zu verknüpfen. Dass sollte sich technisch recht einfach umsetzten lassen und bedeutet weniger manuellen Aufwand.

**Comment by saerdnaer** [comment]
Naja, so vorher-nachher Bilder will man vielleicht anders behandeln als einen Kartenausschnitt.
