### ISSUE TITLE
Bei "Verbundene Stadtratsanträge" nicht nur Titel sondern auch Typ und Fraktion mit anzeigen

### ISSUE THREAD

**Issue by saerdnaer** [codeformunich/Muenchen-Transparent#105]
Mit Typ meinte ich sowas wie "Ergänzungsantrag"

**Comment by konstin** [comment]
> Mit Typ meinte ich sowas wie "Ergänzungsantrag"
 siehe #102. Leider ist diese Information afaik nicht im RIS zu finden. Die Fraktion könnte man aber natürlich noch mit anzeigen.

**Comment by saerdnaer** [comment]
Woher kommt die Info den dann bei https://www.muenchen-transparent.de/antraege/3656074 ? Da steht oben neben Stadtratsantrag noch "Ergänzungsantrag"...

**Comment by konstin** [comment]
Dass es bei manchen Anträgen einen Antragstyp gibt, habe ich vollkommen übersehen...

Bei allen verbundenen Anträgen und Vorlagen werden jetzt - soweit vorhanden - Datum, Fraktion, Typ und Ort mit angezeigt. Mit dem Design bin ich zwar noch nicht so ganz zufrieden, aber im Moment erfüllt es seinen Zweck.

**Comment by saerdnaer** [comment]
Wie ist den der Deployment-Prozess? Also wo kann man sich das wann ansehen?

**Comment by CatoTH** [comment]
Da das momentan noch auf meinem Privatserver läuft, schaut das "Deployment" so aus, dass ich bei Bedarf händisch die Updates vom Repository herunterlade. ^^
Ist jetzt eben geschehen, jetzt sollte es also sichtbar sein.

**Comment by konstin** [comment]
Irgendwie scheint es dabei die Änderungen am css nicht übernommen zu haben, obwohl ich das eig. aktualisiert hatte...

Ich weiß nicht, wie gut das funktioniert, aber mit git+github gibt es anscheinend auch die Möglichkeit, Änderungen automatisch herunterladen zu lassen.

**Comment by CatoTH** [comment]
Ah, sorry, da hatte ich noch einen Befehl übersehen, vergiss insofern auch einfach meine Frage in der Mail eben :)
