### ISSUE TITLE
Bug: Die Funktion "Zeige 1 Dokument..."

### ISSUE THREAD

**Issue by CatoTH** [codeformunich/Muenchen-Transparent#109]
Der Button "Zeige 1 Dokument mit über 10 Ortsbezügen" auf der Startseite funktioniert nicht.

**Comment by konstin** [comment]
In dem Zusammenhang kann man auch noch gleich den komischen weißen Freiraum zwischen  "Zeige 1 Dokument mit über 10 Ortsbezügen" und "So funktioniert Stadtpolitik entfernen"
