### ISSUE TITLE
FR: Weiterblättern bei Suchergebnissen

### ISSUE THREAD

**Issue by CatoTH** [codeformunich/muenchen-transparent#111]
Wenn mehr als X Suchergebnisse gefunden werden, werden nur die ersten Ergebnisse angezeigt - eine Möglichkeit zum Weiterblättern gibt es aktuell nicht. Infinite Scroll dürfte dabei eher schwierig sein, wegen der Zweispaltigkeit.

**Comment by konstin** [comment]
Warum machen wir die Suchergebnisse nicht einfach einspaltig? Das ist imho sowieso angenehmer zum Lesen.

**Comment by akuckartz** [comment]
> Warum machen wir die Suchergebnisse nicht einfach einspaltig? Das ist imho sowieso angenehmer zum Lesen.

:+1:

**Comment by konstin** [comment]
Einspaltig ist es und mehr 50 Ergebnisse anzuschauen ist nicht sinnvoll
