### ISSUE TITLE
Konfiguration für Solr dokumentieren

### ISSUE THREAD

**Issue by konstin** [codeformunich/Muenchen-Transparent#117]
Ich habe es bisher noch nicht geschafft, solr richtig zu konfigurieren, deshalb wäre es sinnvoll, das allgemein zu konfigurieren.

**Comment by konstin** [comment]
Danke!

**Comment by konstin** [comment]
Bei mir funktioniert die Suche jetzt, wobei ich aber die Konfiguration in `solr/example/solr/collection1` speichern und die Dokumente quasi manuell einlesen musste. Interessanterweise habe ich den `/solr` Abschnitt in der nginx-Konfiguration aber nicht gebraucht.

**Comment by CatoTH** [comment]
Das /solr in nginx braucht es bei mir auch nur deshalb, damit ich die HTTP-Authentifizierung und das SSL fürs Web-Interface von Solr über nginx einrichten kann und Solr selbst dafür nur auf localhost horchen lassen kann.
