### ISSUE TITLE
PDF.js: Seiten drehen

### ISSUE THREAD

**Issue by saerdnaer** [codeformunich/muenchen-transparent#118]
Bei einigen Anhängen ist wie z.B. Tabellen oder Karten ist es sinnvoll das PDF bei der Anzeige zu drehen. PDF.js hat die entsprechende Funktion, allerdings muss man erst die Menüleiste erst entsprechend erweitern. Es sinnvoll die Icons anders anzuordnen, so dass die Drehfunktion besser sichtbar wird. 

Bonuspunkte: Speichern wie die Nutzer die Seite gedreht haben und für die anderen Nutzer das Blatt direkt in der richtigen Ausrichtung anzeigen. ;-) Vielleicht auch beim Verlassen der Seite auch fragen, ob die Ausrichtung für zukünftige Betrachter gespeichert werden soll.

**Comment by konstin** [comment]
> Bonuspunkte: Speichern wie die Nutzer die Seite gedreht haben und für die anderen Nutzer das Blatt direkt in der richtigen Ausrichtung anzeigen. ;-) Vielleicht auch beim Verlassen der Seite auch fragen, ob die Ausrichtung für zukünftige Betrachter gespeichert werden soll.

Das ist wahrscheinlich nur über Umwege in javascript möglich, die ich lieber vermeiden möchte, auch weil nur relativ wenig Dokumente betroffen sind. Die Positionierung der Buttons werde ich mir aber nochmal anschauen.
