### ISSUE TITLE
Startseite: Karte durch Erklärungsvideo ersetzen

### ISSUE THREAD

**Issue by saerdnaer** [codeformunich/Muenchen-Transparent#119]

**Comment by konstin** [comment]
So ganz überzeugt bin ich davon noch nicht, aber wir das so machen, dann sollte das Video nur Personen angezeigt werden, die die Seite zum ersten mal besuchen.

Die Karte auf der Startseite bietet nämlich den großen Vorteil, dass jeder (Münchner) direkt die Ereignisse in seiner Nähe sehen kann. Das dürfte für viele Besucher am Anfang interessanter sein als die Vorgänge in der Stadtpolitik erklärt zu bekommen. Außerdem erwartet man von einem so platzierten Video, dass es einem Informationen zur Seite bzw. zum Projekt liefert.

**Comment by akuckartz** [comment]
:-1:

**Comment by saerdnaer** [comment]
Okay, vielleicht sollte man dann da ein extra Video machen das einfach nur erklärt wie man die Seite benutzt. Wenn ich aktuell den Leuten die Seite zum ersten mal zeigen sind sie jedesmal von der Karte auf der Startseite erst mal verwirrt.

**Comment by konstin** [comment]
Ich finde die Karte einen deutlich größeren Wert für die Nutzer hat und außerdem deutlich besser aussieht. Eine Art Einführung für neue Nutzer wäre tatsächlich eine gute Idee, aber das wäre dann nochmal eine eingene Aufgabe.
