### ISSUE TITLE
Zeitangaben in MySQL von TIMESTAMP auf DATETIME umstellen (Zeitzonen)

### ISSUE THREAD

**Issue by konstin** [codeformunich/muenchen-transparent#128]
Wenn bei MySQL eine andere Zeitzone eingestellt wird, dann ändern sich die Zeitangaben von Terminen. Wenn wir jedoch statt TIMESTAMP DATETIME verwenden, dann bleiben die Termine in allen Zeitzonen gleich, was imo sinnvoller ist.

@CatoTH Wie siehst du das?

**Comment by CatoTH** [comment]
Oder einfach nochmal explizit die richtige Zeitzone in der Verbindung setzen für den Fall, dass der Server "falsch" konfiguriert ist? Andere Möglichkeit wäre, das Datum beim Auslesen explizit in die aktuelle Zeitzone zu bringen, aber das geht glaub ich übers Yii-ActiveRecord nur umständlich. DATETIME geht natürlich auch, ist halt nur minimal unperformanter (weils mehr Speicherplatz braucht).

**Comment by konstin** [comment]
Ich halte DATETIME auch deshalb für sinnvoller, weil es die Daten aus dem RIS genauer wiedergibt und wir damit nicht die Beschränkung von TIMESTAMP auf den Bereich 1970 - 2038 haben. Außerdem werden dadurch jedliche mögliche Probleme mit Zeitzonen ausgeschlossen, was mich der entscheidende Vorteil ist.
