### ISSUE TITLE
Zugriff auf /shariffData gibt code 500

### ISSUE THREAD

**Issue by konstin** [codeformunich/Muenchen-Transparent#130]
s. https://www.muenchen-transparent.de/shariffData?url=https://www.muenchen-transparent.de/antraege/3896633

**Comment by CatoTH** [comment]
Lag an Twitter - mit https://github.com/codeformunich/Muenchen-Transparent/commit/b0c0f5d3c76745d36696951513931e03264a6d49 behoben
