### ISSUE TITLE
Fehlende Dokumente bei Stadtratsvorlage

### ISSUE THREAD

**Issue by konstin** [codeformunich/muenchen-transparent#144]
Bei https://www.muenchen-transparent.de/antraege/4169494 fehlen die im RIS vorhandenen Dokumente.

**Comment by CatoTH** [comment]
ach je, auch gerade das...
Problem ist wohl, dass die Dokumente zeitweise nicht mehr verfügbar waren und deswegen als gelöscht markiert waren. Ich schaue, dass ich jetzt mal alle Dokumente "entlösche", die so versehentlich als gelöscht markiert wurden.
