### ISSUE TITLE
Hindernisse auf dem Weg zu leipzig-transparent

### ISSUE THREAD

**Issue by gerbsen** [codeformunich/muenchen-transparent#149]
Hallo liebes muenchen-transparent-Team,
Zunächst mal vielen dank für euer Engagment! Das Tool sieht wirklich super cool aus! Ich hab mich letztens mit Ernesto unterhalten und er hat mich auf die zauberhafte Welt von OParl hingewiesen. Ich habe mir jetzt ein Quote von Hersteller eingeholt (deutlich billiger als erwartet) und würde jetzt gern daran gehen einen Antrag für meine Partei zu schreiben um ihn möglichst bald auch im Stadtrat einbringen zu können. Wenn ich das jetzt richtig verstanden haben, setzt "muenchen-transparent" auf die OParl Schnittstelle auf (in unserem Fall AllRIS) und extrahiert darüber (regelmäßig) Daten. Da kommen mir jetzt noch folgende Fragen:

1. Habt ihr schon mal `muenchen-transparent` auf andere Städte portiert? Was wäre denn da noch zu tun? Gibt es größere Hindernisse als Texte und GeoJson zu ändern?
2. Was habt ihr für Systemanforderungen? Ich könnte mir vorstellen das die den Volltextindex da schon einiges zusammenkommt?
3. Arbeitet ihr zufälligerweise schon an einem Docker-Install? (Würde gern dabei helfen)

Ich weiß, dass das nicht wirklich ein echtes Issue ist, ich hoffe ihr verzeiht mir diesen Eintrag hier. (Wo wäre der korrekt Kanal?)

Vielen Dank für eure Infos,
Daniel

**Comment by gerbsen** [comment]
Okay, Frage 3) hab ich mir selbst beantwortet: https://github.com/codeformunich/muenchen-transparent/blob/docker/docker-compose.yml

**Comment by konstin** [comment]
Hallo Daniel,

wir freuen uns über dein Interesse an München Transparent!. München Transparent selbst ist leider nicht auf andere Städte übertragbar, da es zu stark auf München angepasst ist.

Wir arbeiten aber momentan am Nachfolger, genannt [Meine Stadt Transparent](https://github.com/meine-stadt-transparent/meine-stadt-transparent) ([Demo](https://meine-stadt-transparent.de/)). Meine Stadt Transparent soll sich in beliebigen Städte einsetzen lassen und setzt für den Import komplett auf OParl.

Zu 1: Der Einrichtungsaufwand ist im Idealfall ein Befehl. In der Praxis muss man immer noch etwas Nachjustieren, z.B. weil Daten fehlen oder die Implementierung nicht ganz Standard-konform ist.

Zu 2: Im Moment sind das bei Meine Stadt Transparent mariadb, elasticsearch und das recht genügsame gunicorn. In der Praxis bedeutet das, dass genügend RAM für elasticsearch vorhanden sein muss.

Zu 3: Bei Meine Stadt Transparent ist docker compose der empfohlene Installationsweg. Wir nehmen aber gerne Hilfe beim Testen, da wird man nämlich leicht betriebsblind ;)

Für alles weitere schreib uns am Besten eine E-Mail an info@meine-stadt-transparent.de, da können wir dann auch alle Details klären.

Viele Grüße
  Konstantin

**Comment by gerbsen** [comment]
Gut, dann führen wir es sort weiter, danke schon mal!
