### ISSUE TITLE
OParl missing data for current legislative term

### ISSUE THREAD

**Issue by darkdragon-001** [codeformunich/muenchen-transparent#158]
The data for the current legislative term 2020-2026 is not available via OParl:
```sh
curl https://www.muenchen-transparent.de/oparl/v1.0/body/0 | jq
```

<details><summary>Output</summary>

```json
{
  "id": "https://www.muenchen-transparent.de/oparl/v1.0/body/0",
  "type": "https://schema.oparl.org/1.0/Body",
  "system": "https://www.muenchen-transparent.de/oparl/v1.0",
  "contactEmail": "info@muenchen-transparent.de",
  "contactName": "München Transparent",
  "name": "Stadrat der Landeshauptstadt München",
  "shortName": "Stadtrat",
  "website": "https://www.muenchen.de/rathaus/",
  "legislativeTerm": [
    {
      "type": "https://schema.oparl.org/1.0/LegislativeTerm",
      "name": "Unbekannt",
      "startDate": "0000-00-00",
      "endDate": "0000-00-00",
      "id": "https://www.muenchen-transparent.de/oparl/v1.0/legislativeterm/0"
    },
    {
      "type": "https://schema.oparl.org/1.0/LegislativeTerm",
      "name": "1996-2002",
      "startDate": "1996-12-03",
      "endDate": "2002-12-03",
      "id": "https://www.muenchen-transparent.de/oparl/v1.0/legislativeterm/1"
    },
    {
      "type": "https://schema.oparl.org/1.0/LegislativeTerm",
      "name": "2002-2008",
      "startDate": "2002-12-03",
      "endDate": "2008-12-03",
      "id": "https://www.muenchen-transparent.de/oparl/v1.0/legislativeterm/2"
    },
    {
      "type": "https://schema.oparl.org/1.0/LegislativeTerm",
      "name": "2008-2014",
      "startDate": "2008-12-03",
      "endDate": "2014-12-03",
      "id": "https://www.muenchen-transparent.de/oparl/v1.0/legislativeterm/3"
    },
    {
      "type": "https://schema.oparl.org/1.0/LegislativeTerm",
      "name": "2014-2020",
      "startDate": "2014-12-03",
      "endDate": "2020-12-03",
      "id": "https://www.muenchen-transparent.de/oparl/v1.0/legislativeterm/4"
    }
  ],
  "organization": "https://www.muenchen-transparent.de/oparl/v1.0/body/0/list/organization",
  "person": "https://www.muenchen-transparent.de/oparl/v1.0/body/0/list/person",
  "meeting": "https://www.muenchen-transparent.de/oparl/v1.0/body/0/list/meeting",
  "paper": "https://www.muenchen-transparent.de/oparl/v1.0/body/0/list/paper",
  "web": "https://www.muenchen-transparent.de/",
  "created": "2016-10-16T20:38:18+02:00",
  "modified": "2016-10-16T20:39:16+02:00",
  "ags": "09162000",
  "rgs": "606109162000"
}
```

</details>

**Comment by konstin** [comment]
The legislative term data is hardcoded across the codebase,  [here](https://github.com/codeformunich/muenchen-transparent/blob/e35224a0bd547ae374f391e9b3e6a05dfbe0e62a/protected/models/Wahlperioden.php#L14-L19) is the one the html version uses, [here](https://github.com/codeformunich/muenchen-transparent/blob/5a1873503d57bdfd310ceb36c6d4b4d55acf6e30/protected/components/OParl10Object.php#L192-L197) is the one that the oparl api use. personally, i don't plan any significant updates on München Transparent though, all effort now goes towards [Meine Stadt Transparent](https://github.com/meine-stadt-transparent/meine-stadt-transparent) and getting cities to implement OParl

**Comment by darkdragon-001** [comment]
Will the people list be updated when I add the missing legislative terms?

I totally agree with your focus. Unfortunately, Munich just got a new system this year which does not implement OParl. Would it make sense to just keep the scraper+database+OParl for Munich and put Meine Stadt Transparent behind this API? This way one would not need to maintain the php code for München Transparent...

**Comment by konstin** [comment]
For the foreseeable future, it makes most sense for us if munich sticks with münchen transparent as-in; though in general, it's @CatoTH's call what changes will go into münchen transparent
