### ISSUE TITLE
API auf Basis von OParl

### ISSUE THREAD

**Issue by CatoTH** [codeformunich/muenchen-transparent#42]
Eine API auf OParl-Basis wäre sinnvoll, um Dritten die Entwicklung einer App auf Basis unseres Datenbestands zu ermöglichen. Die zugrundeliegende Datenstruktur der Spezifikation unter http://oparl.org/ wirkte bei erster Inaugenscheinnahme flexibel genug, um unser Datenmodell abzubilden, wenn sich auch vieles an (wichtiger) Funktionalität noch nicht in die Spezifikation eingeflossen ist (z.B. eine Suche).

Empfohlenes Vorgehen: warten, bis entweder der OParl-Standard offiziell verabschiedet ist, oder sich jemand meldet, der Interesse an einer solchen API hat.

**Comment by akuckartz** [comment]
Wie man u.a. an https://github.com/OParl/specs/issues/261 sehen kann, ist OParl als Spezifikationsprojekt praktisch eingeschlafen und/oder ist ein Musterbeispiel für Intransparenz.

Die Arbeiten werden in OpenGovLD (https://github.com/OpenGovLD/specs/wiki) im Rahmen der W3C Open Government Community Group fortgesetzt. Eine Arbeitsversion gibt es voraussichtlich innerhalb der nächsten Wochen. https://politik-bei-uns.de wird möglicherweise bereits im Sommer solche Export/Import-Schnittstellen erhalten (https://github.com/okfde/ris-web/wiki/OpenGovLD).

@CatoTH 
> wenn sich auch vieles an (wichtiger) Funktionalität noch nicht in die Spezifikation eingeflossen ist

Was ist damit - neben Unterstützung von Suchmöglichkeiten - gemeint? Input über https://github.com/OpenGovLD/specs/issues wäre sehr willkommen!

**Comment by CatoTH** [comment]
@akuckartz Ok, ich werde mir das die Tage genauer anschauen.

Weißt du denn schon von irgendwelchen Initiativen, die das entweder in produktiven Systemen einbauen oder aber Clients auf der Basis entwickeln? (Ist wahrscheinlich noch etwas früh dafür, oder?)

**Comment by akuckartz** [comment]
@CatoTH Da muss ich mit einem klaren "Jein" antworten. Nein, denn die Erstellung der Arbeitsversion von OpenGovLD dauert noch etwas.

_Aber_: Ich hatte in der Zeit, als ich bei OParl mitgewirkt hatte, Teile von Popolo (http://www.popoloproject.com/) in OParl einfliessen lassen (die wiederum teilweise auf anderen Vokabularen beruhen).

JSON-Serialisierungen entsprechend Popolo werden weltweit bereits in diversen Projekten verwendet. Serialisierungen von Popolo in JSON-LD sind ebenfalls spezifiziert, aber bisher wenig genutzt. OpenGovLD soll auch dabei helfen das ändern und dabei die Ausdruckskraft von Popolo und OParl vereinigen.

**Comment by konstin** [comment]
Plant ihr eigentlich OParl/specs in OpenGovLD/specs zu mergen oder muss man sich langfristig für Eins von Beiden entscheiden? Denn anscheinend schreibt "marians" noch an der Spezifikation, kümmert sich aber seit einem halben Jahr nicht mehr um die Issues oder den OParl-Blog.

**Comment by akuckartz** [comment]
@konstin "Mergen" tifft es sehr gut. OParl hatte zum Ziel die Gemeinsamkeiten (kleinster gemeinsamer Nenner) der in Deutschland bisher verwendeten RIS-Produkte abzudecken. OpenGovLD will darüber hinaus auch solche Daten abdecken, die nur von einzelnen Systemen unterstützt werden. Zudem ist OpenGovLD ohnehin nicht auf Deutschland beschränkt. Die Mächtigkeit wird deshalb größer sein als die von OParl.

Gleichzeitig soll es bei OpenGovLD keine (scheinbaren) vorzeitigen Optimierungen oder (scheinbaren) Abkürzungen geben. Dort steht Nachhaltigkeit und die Verwendung aktueller Standards im Vordergrund.

In OParl wurden Ende Juni/Anfang Juli 2014 Änderungen vorgenommen, die Ergebnis einer anderen Ausrichtung sind. Deshalb hatte ich mich am 4.7.2015 daraus zurückgezogen und OpenGovLD abgespalten.

Die OParl-Initiatoren haben seit September 2014 auf wiederholte mails mit Angeboten der Koordinierung nicht reagiert. Insoweit kann ich zur zukünftigen Entwicklung von OParl nichts sagen. Wenn man die letzten 7 Monate extrapoliert, dann kann man aber vorhersagen, dass sich dort so bald nichts verändern wird. Das Gebilde "OParl" lebt allerdings insoweit noch, als der gut gewählte Name immer wieder mal erwähnt wird und mit bekannten Institutionen in Verbindung steht (die sich - wenn überhaupt - aber nur sehr geringfügig an der Erarbeitung Spezifikation beteiligt hatten).

Nein, Marian schreibt nicht an der Spezifikation (wenn man seine Aktivitäten auf GitHub ansieht). Er hat jedoch vor 10 Tagen einen Pull-Request ohne Änderung gemerged. Der Vorgang ist interessant, da dadurch _nichts_ verbessert wurde, sondern nur vier offene Fragen entfernt wurden ohne diese zu beantworten oder sie auch nur im Issue-Tracker festzuhalten.

**Comment by konstin** [comment]
Danke für die ausführliche Anwort. Wenn @CatoTH nichts dagegen hat, dann wäre ich dafür, OpenGovLD statt OParl zu implementieren und das auch beim nächsten Code for München Treffen am Donnerstag zu kommunizieren. Wobei das mit der Implementierung noch etwas dauern könnte, weil Spezifikation in code umzusetzen nicht gerade die spannenste Aufgabe ist.

**Comment by akuckartz** [comment]
@konstin OpenGovLD benötigt ja auch noch etwas Zeit! Inzwischen ist das weitgehend "nur" noch Fleissarbeit, aber auch die kostet Zeit...

Die Spezifikation soll zwar einfach sein (was ihre Entwicklung aufwändig macht), dennoch wird es Teile geben, deren Umsetzung man je nach Interessenlage als spannend ansehen kann ;-)

Motivieren kann möglicherweise auch die Aussicht, dass die Daten dann ab voraussichtlich Sommer 2015 auch in politik-bei-uns.de importiert werden können.

**Comment by akuckartz** [comment]
Ein kurzer Hinweis, um anzudeuten weshalb die Implementierung der OpenGovLD-Spezifikation durchaus "spannend" sein kann: Der Hauptteil der Spezifikation wird _maschinenlesbar_ in Hydra (http://www.hydra-cg.com/spec/latest/core/) beschrieben sein.

Ein einfacher _generischer_ Client ist die Hydra Console (http://www.markus-lanthaler.com/hydra/console/). Mit dessen Hilfe kann man z.B. eine exemplarisch angebotene Event-API (http://www.markus-lanthaler.com/hydra/event-api/) ansteuern:
http://www.markus-lanthaler.com/hydra/console/?url=http://www.markus-lanthaler.com/hydra/event-api/

Oder aber eine Demo Issue-tracker API:
http://www.markus-lanthaler.com/hydra/console/?url=http://www.markus-lanthaler.com/hydra/api-demo/

Bei Interesse daran gibt es hier weitere Informationen: http://www.hydra-cg.com/

Ich plane für Anfang nächster Woche die Verfügbarmachung einer Teilspezifikation von OpenGovLD. Ich schaue mal, was mir dafür nach weiterer Durchsicht von Muenchen-Transparent geeignet erscheint. Oder ihr macht Vorschläge ;-)

**Comment by konstin** [comment]
Gelöst durch #138
