### ISSUE TITLE
Doppelte und Dreifache Dokumente

### ISSUE THREAD

**Issue by konstin** [codeformunich/Muenchen-Transparent#56]
Anscheindend gibt es im RIS einige Dokumente dreifach, wie z.B. "Einladung Plenum (oeff)" in https://www.ratsinformant.de/termine/3212121. Auch wenn das wahrscheinlich ein Fehler des RIS ist, solten wir trotzdem doppelte Dokumente rausfiltern (z.B. über Hash-Werte).

**Comment by CatoTH** [comment]
Ich befürchte fast, das lässt sich nicht wirklich praktikabel automatisiert umsetzen; es gibt auch Fälle, wo später mal nur das Deckblatt hochgeladen wird uns es dann eher ungünstig wäre, wenn alte nicht mehr sichtbar sind. Behaupten wir einfach mal, das ist ein Feature, kein Bug: so sieht man manchmal, was sich über die Zeit an der Tagesordnung so geändert hat - das kann ja durchaus auch interessant sein. :-)

**Comment by konstin** [comment]
Wir könnten auch einfach das layout ändern. Z.B.:

 * Einladung Plenum (öff): [03.07.2014](https://www.muenchen-transparent.de/dokumente/3364429) [01.07.2014](https://www.muenchen-transparent.de/dokumente/3362962) [30.06.2014](https://www.muenchen-transparent.de/dokumente/3364429)

Der Breadcrumb in der Dokumentenanzeige muss in dem Fall natürlich auch angepasst werden.
