### ISSUE TITLE
Tabellen exportieren

### ISSUE THREAD

**Issue by konstin** [codeformunich/Muenchen-Transparent#69]
Um an einer lokalen Version von München Transparent entwickeln können, braucht man neben `schema3.sql` und `init_data/*.sql` noch einige Tabellen, wie z.B. `texte` oder `referate`. Deshalb wäre es sinnvoll, alle unkritischen Tabellen zu exportieren und entweder ins repository einzupflegen oder zum download zur Verfügung zu stellen.

Ich fände es am sinnvollsten, einfach ein php-script zu schreiben, das auf Anfrage eine freigegebene Tabellen exportiert. (z.B. per Aufruf von `ratsinformant.de/tabellen/texte.sql`)

**Comment by akuckartz** [comment]
Was sind "unkritische" Tabellen ?

**Comment by CatoTH** [comment]
@akuckartz Vor allem die BenutzerInnen-Accounts wären kritisch.

**Comment by konstin** [comment]
Unkritisch sind alle Daten, auf die niemand einen Urheberrechtanspruch geltend machen kann und die keine Sicherheitsrelevanten Informationen enthalten. Das wären z.B. unsere eigenen Texte, die Gremienliste oder die Bezirkssausschussliste.
