### ISSUE TITLE
Entscheiden, ob für Einrückungen Leerzeichen oder Tabs genutzt werden sollen

### ISSUE THREAD

**Issue by konstin** [codeformunich/Muenchen-Transparent#72]
Mir persöhnlich wären nur Leerzeichen lieber (dann wäre die Einrückungsweise indentisch mit der von scss). Wichtig ist aber, dass wir uns überhaupt auf einen Standart einigen, denn bei mir hat git gerade das mergen verweigert, weil d4d15481804d88109e95803496ecd46b9d129241 die Einrückungsweise des Index-Controllers geändert hat.

**Comment by CatoTH** [comment]
Können wir schon machen. Ich persönlich bin zwar eher der Freund von Tabs, wegen flexibler Breite. Und ich wollte jetzt schon argumentieren, dass das Yii-Framework auch Tabs verwendet. Dummerweise steigt die neue große Version 2 von Tabs auf 4-Leerzeichen um, also befürchte ich, dass der Zug wirklich eher in die 4-Leerzeichen-Richtung... :)

**Comment by CatoTH** [comment]
Ok, dann also:
- 4 Leerzeichen pro Einrückung
- Geschweifte Klammern bei Funktionen/Methoden in eigene Zeile
- Bei mehreren Zuweisungen hintereinander die = aneinander ausrichten.

Ich hab das jetzt per automatischer Code-Formatierung bei den regulären PHP-Dateien gemacht und committed. Bei den Views mal noch nicht, weil mir da die Code-Formatierung leider gelegentlich auch den HTML-Code zerschießt...

Ich würde sagen, dass wir dann mittelfristig auch mal so eine automatische Code-Prüfung einführen, die sich beschwert, wenn Code committed wird, der nicht gültig ist.
Für die Validierung dürfte PHP Code Sniffer da das beste sein, als technische Plattform für die automatische Prüfung schauen mir jetzt phptesting.org und Jenkins mit am geeignetsten aus (bei Travis hab ich jetzt auf Anhieb nicht gesehen, wie gut sich das für PHP einsetzen lässt...)
