### ISSUE TITLE
breadcrumb is nach Seitenwechsel in pdf.js nur noch zur Hälfte zu sehen

### ISSUE THREAD

**Issue by konstin** [codeformunich/Muenchen-Transparent#79]
Das Problem tritt  sowohl in firefox als auch in chrome bei Dokumenten mit mehr als einer Seite (z.B. https://www.muenchen-transparent.de/dokumente/3563896) auf: Wenn man bis zur nächsten Seite herunter scrollt, verschwindet die Hälfte des breadcrumbs Bei sehr langen pdf's (z.B. https://www.muenchen-transparent.de/dokumente/3473795) sieht alles richtig aus.

Das Verhalten ist unabhängig von den Werten in `dokumentenanzeige.php` ab Zeile 70. Der breadcrumb bleibt allerdings sichtbar, wenn ich den `#content > section.well.pdfjs`-Abschnitt in `_styles.scss` auskommentiere. Dabei geht aber leider auch der Rest der Formatierung verloren.

**Comment by CatoTH** [comment]
Schau zur Sicherheit auch nochmal nach, aber bei mir tritt der Fehler nun nicht mehr auf.

**Comment by konstin** [comment]
Bei existiert der Fehler immernoch, sowohl lokal mit dem neusten master als auch auf muenchen-transparent.de.

**Comment by CatoTH** [comment]
Auch nach einem Reload? Bzw. ist das "overflow: hidden" bei 
#content > section.well.pdfjs
noch da oder schon weg?

**Comment by konstin** [comment]
Alles neuladen bringt Vorteile ...

Nach einem Neustart von firefox ist der bug verschwunden.
