### ISSUE TITLE
Stadtrats-Live-Streams ankündigen

### ISSUE THREAD

**Issue by CatoTH** [codeformunich/muenchen-transparent#81]
Live-Streams von Stadtratssitzungen (http://www.muenchen.de/rathaus/Stadtpolitik/Der-Muenchner-Stadtrat/Der-Muenchner-Stadtrat-live.html) könnten wir auf der Startseite auch mit ankündigen.

**Comment by saerdnaer** [comment]
Eigentlich könnte man auch die Aufzeichnungen mit der entsprechenden Sitzung verknüpfen. Oder ist immer nur die letzte Sitzung online als Video abrufbar?

**Comment by konstin** [comment]
Afaik ist offiziell immer nur die letzte Sitzung abrufbar.
