### ISSUE TITLE
Fehlerhafte Links

### ISSUE THREAD

**Issue by CatoTH** [codeformunich/Muenchen-Transparent#83]
Kam als Feedback rein:

Bei den Terminen:
  - Kinder und Jugendausschuss am 13.01,
  - Gesundheitsausschuss am 22.01,
   - Stadtplanung und Ordnung am 28.01,
Stimmen die Links nicht: https://www.muenchen-transparent.de/termine/3448082,/termine/3506980

**Comment by konstin** [comment]
Ist das nicht schon mal (Hackday?) gefixt worden? Das Problem hatte ich nämlich bereits früher entdeckt.
