### ISSUE TITLE
Druck verbessern

### ISSUE THREAD

**Issue by CatoTH** [codeformunich/Muenchen-Transparent#89]
Beim Ausdruck eines PDFs über PDF.JS gibt es doch einige Unstimmigkeiten, z.B. ein fast leeres Deckblatt und nicht ganz korrekt gesetzte Seitenränder.

**Comment by CatoTH** [comment]
Teilweise abgemildert durch https://github.com/codeformunich/Muenchen-Transparent/commit/c4f7e21cd160e6cbe64915053cb7fcfc24e6c439 ; Das Drucken der Seite mit dem Inline-PDF ist aber immer noch ziemlich kaputt.

**Comment by konstin** [comment]
Imho ist die momentane Lösung ausreichend.
