### ISSUE TITLE
Anwortschreiben werden nicht als solche angezeigt.

### ISSUE THREAD

**Issue by konstin** [codeformunich/Muenchen-Transparent#90]
Seit neustem werden einige Antwortschreiben nicht mehr als solche angezeigt, u.a. https://www.muenchen-transparent.de/dokumente/3584890 und https://www.muenchen-transparent.de/dokumente/3584905.

**Comment by konstin** [comment]
Noch ein Beispiel, weil dieser Fall besonders verwirrend ist: https://www.muenchen-transparent.de/antraege/3529129

**Comment by CatoTH** [comment]
Scheint daran zu liegen, dass das Dokument im RIS als "Antrag_506_Gemeinschaftsunterkuenfte bedarfsgerecht und nachhaltig gestalten" eingetragen ist. Immerhin im title-Attribut des Links scheint noch das "Antwortschreiben" zu stehen. Ich werd schauen, das im Parser mit zu berücksichtigen.

**Comment by CatoTH** [comment]
Ist jetzt behoben.
