### ISSUE TITLE
Menü-Dropdown wird von PDF-Menü überlagert

### ISSUE THREAD

**Issue by stekhn** [codeformunich/Muenchen-Transparent#93]
Wenn man eine Dokument liest und das Dropdown öffnet, wird das Dropdown durch das PDF-Menü überlagert. Passiert in allen aktuellen Browser unter Windows und Mac OS X.

![layoutbug](https://cloud.githubusercontent.com/assets/1587837/6128476/8c037a3c-b136-11e4-9cee-c1b43b02bfd0.jpg)

**Comment by CatoTH** [comment]
Danke für den Hinweis. Sollte jetzt (ggf. nach einem Reload mit F5) behoben sein. :)

**Comment by konstin** [comment]
Sorry, das hatte ich nach dem update von pdf.js wohl vergessen...
