### ISSUE TITLE
Schlagworte: Feedback

### ISSUE THREAD

**Issue by CatoTH** [codeformunich/Muenchen-Transparent#96]
Das hier kam eben per Feedback-Funktion rein:

```Im Teil "Themen" steht die Auflistung der "Schlagworte". Diese Sortierung nach Anzahl Treffer o.ä. ist nicht nützlich. Man sucht sich einen Wolf, wenn man sich für ein bestimmtes Schlagwort interessiert. Es sollte nach Schlagwort sortiert sein.
Dass dann die zugehörigen Anträge gezeigt werden, erfährt man erst, wenn man die Applikation kennt, andernfalls ist unklar was unter den Stichworten kommen wird.```

**Comment by akuckartz** [comment]
Eine eventuelle Alternative: Nur die Top-10 oder Top-5 nach Verwendungs-Häufigkeit auflisten und darunter den Rest in lexikographischer Ordnung.

Dass beim Klick auf ein Schlagwort zugehörige Anträge aufgelistet werden finde ich naheliegend.

Unklar ist mir aber die Beziehung zwischen den Schlagworten. Sind z.B. "IT@M", "LiMux", "IT-Multiprojektmanagement", "IT-Projekte" und "Open Data" Spezialisierungen von "IT" oder unabhängig von einander?

Wer erstellt die Schlagworte bzw. ordnet sie zu?

(Für mich als Suchhilfe ein Stichwort: SKOS)

**Comment by konstin** [comment]
> Man sucht sich einen Wolf, wenn man sich für ein bestimmtes Schlagwort interessiert.

Genau dafür habe ich das "Filtern"-Feld eingebaut. Damit findet man bestimmte Begriffe meistens sogar deutlich schneller als nur mit alphabetischer Sortierung.

> Dass dann die zugehörigen Anträge gezeigt werden, erfährt man erst, wenn man die Applikation kennt, andernfalls ist unklar was unter den Stichworten kommen wird.

In dem Fall sollte es zumutbar sein, einmal auf das Schlagwort zu klicken, um heraus zu finden, dass sich dort die Anträge mit dem tag verbergen. Ansonsten kann man immernoch über die link-Beschreibung (title-tag in html?) erklären, was sich dort verbirgt.

@akuckartz Über das Problem von Schlagwort-Beziehungen habe ich auch schon nachgedacht, aber noch keine gute Lösung gefunden. Ich versuche einfach immer das/die am besten passenden tag(s) zu finden und bis jetzt hat das recht gut funktioniert. Teilweise lösche ich aber auch zu unwichtige oder nichtssagende tags einfach wieder. Bei https://www.muenchen-transparent.de/antraege/3363105 habe übrigens auch nicht ich die tags gesetzt.

**Comment by akuckartz** [comment]
@konstin Ich bin an dezentralen Thesauren interessiert, die über einzelne Gebietskörperschaften hinaus gehen. Die Pflege von Beziehungen zwischen Schlagworten kann dabei auch ausgelagert werden. Wenn ich einen konkreten Vorschlag habe, dann melde ich mich.
