### ISSUE TITLE
Passwort Reset nicht möglich

### ISSUE THREAD

**Issue by lhampe** [codeformunich/Muenchen-Transparent#99]
Hallo,

ich wollte mein Passwort [auf dieser Website] (https://www.muenchen-transparent.de/resetPasswordForm) zurück setzen.

Leider bekomme ich (egal ob e-Mail adresse eingetragen, oder nicht) folgende Fehlermeldung:
```
 The system is unable to find the requested action "resetPasswordForm". 
```
![muc_transparent-pw_reset_fail](https://cloud.githubusercontent.com/assets/5237513/6781694/c69079da-d16f-11e4-868f-4d434ff9116a.jpg)

Wär cool, wenn sich das mal jmd anschaut und im optimalfall gleich fixt ;)

Die Website gefällt mir ansonsten sehr gut - finde es cool, was ihr macht!

Viele Grüße
Lukas

**Comment by lhampe** [comment]
*weitere Infos*
* https://www.muenchen-transparent.de/resetPasswordForm scheint mir ein permanenter Link zu sein, der eher nix mit meinem User zu tun hat (bin ja nicht eingeloggt)
* Es ist möglich, das ich mich auf der [Ratsinformant Site] (http://ratsinformant.de/) registriert habe - weiß ich leider nicht mehr

**Comment by konstin** [comment]
Vielen Dank für den Hinweis! Anscheinend habe ich bei der letzten Änderung vergessen das Passwort Zurücksetzen zu testen...

Ich habe das jetzt mal in 3cf6463 versucht, das Problem zu beheben. Ich muss aber noch warten, bis die Änderungen auf dem Server landen, um dann mit den E-Mails vom Server alles zu testen.

Ich lasse den Issue noch solange offen, bis ich sicher bin, das alles ordentlich funktioniert.

**Comment by CatoTH** [comment]
@konstin ist, ist eingespielt :)

**Comment by lhampe** [comment]
@konstin & @CatoTH Vielen dank für den schnellen Fix !
...hab soeben mein Passwort resettet - funktioniert wieder einwandfrei :smile:
